name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: wevm/actions/.github/actions/pnpm@main

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.0.30
